spring:
  application:
    name: @project.artifactId@

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false